"""Environment field from real ISRO data — CLAUDE.md layer 1, the forcing half.

    python -m samudra.ingest.environment --incident demo-001
    python -m samudra.ingest.environment --bounds 68,21,71,24 --hours 24 \
        --out artifacts/<id>/env.npz

WHAT THIS REPLACES. Until now every `env.npz` in the project was generated by
`synth/generate.py` — smooth random fields constrained to plausible speeds. The
drift model and the 3-10 m/s detection gate both ran on invented numbers. This
module fills the WIND half with a real measurement.

WIND IS REAL. CURRENT IS NOT. That split is the whole point of this docstring.

    wind     EOS-06 (Oceansat-3) OSCAT-3, product E06SCT_L4_AWV6HOURLY:
             analysed vector wind on a global 0.25 degree grid, 6-hourly,
             retrieved from MOSDAC with an approved account. u and v are in
             m/s, CF-1.4, and are used exactly as published.

    current  SYNTHETIC. MOSDAC publishes no ocean-current product in the set
             this project consumes, and INCOIS's open archive stops in 2023. A
             smooth field with realistic magnitude is generated instead, and
             `env_provenance.json` says so in as many words. Do not let a
             dossier imply the current was measured.

WHY L4 AND NOT THE L2B SWATH. A raw L2B swath is one ~1800 km strip at one
instant. Measured on the real product: a granule the catalogue returned for a
Gulf of Kutch bounding box actually spanned 72.4 E eastward and contained ZERO
cells over the AOI. Swaths miss most AOIs most of the time. L4 is the gridded
analysis built for forcing models, which is what this is for.

THE GATE IS NOT COSMETIC. First real retrieval over the Gulf of Kutch gave
11.87 m/s, which is ABOVE the 3-10 m/s window in CLAUDE.md 5.2 — so with real
wind the detection gate legitimately fails there. That is a result, not a bug,
and it is the kind of answer a synthetic field can never produce.
"""

from __future__ import annotations

import argparse
import json
import math
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any

import numpy as np

WIND_DATASET = "E06SCT_L4_AWV6HOURLY"
CACHE_DIR = Path("data/raw/mosdac")

#: Current magnitude for the synthetic half. Typical open-shelf surface current
#: in the northern Arabian Sea; it is a plausible magnitude, not a measurement.
CURRENT_SPEED_RANGE_MS = (0.10, 0.35)


def _fill_to_nan(arr: np.ndarray, fill) -> np.ndarray:
    a = np.asarray(arr, dtype=float)
    if fill is None:
        return a
    # The published fill is -999000000.0; compare loosely so a float32 round
    # trip cannot leave a sentinel behind masquerading as a 1e9 m/s wind.
    return np.where(np.abs(a - float(fill)) < 1.0, np.nan, a)


def read_l4_wind(path: Path, bounds) -> dict[str, Any]:
    """Read one L4 file and crop to `bounds`. Returns lats/lons/u/v/time."""
    from scipy.io import netcdf_file

    min_lon, min_lat, max_lon, max_lat = bounds
    with netcdf_file(str(path), "r", mmap=False) as nc:
        lat = np.asarray(nc.variables["lat"][:], dtype=float)
        lon = np.asarray(nc.variables["lon"][:], dtype=float)
        uv = nc.variables["u"]
        vv = nc.variables["v"]
        fill = uv._attributes.get("_FillValue")
        u = _fill_to_nan(uv[:], fill)
        v = _fill_to_nan(vv[:], fill)
        tvar = nc.variables["time"]
        tunits = tvar._attributes.get("units", b"")
        tunits = tunits.decode() if isinstance(tunits, bytes) else tunits
        toffs = np.asarray(tvar[:], dtype=float)

    # The grid is 0..360; an AOI stated in -180..180 has to be matched in the
    # grid's own convention or the crop silently comes back empty.
    q_min = min_lon % 360.0
    q_max = max_lon % 360.0
    ia = np.where((lat >= min_lat) & (lat <= max_lat))[0]
    if q_min <= q_max:
        io = np.where((lon >= q_min) & (lon <= q_max))[0]
    else:  # AOI straddles the antimeridian
        io = np.where((lon >= q_min) | (lon <= q_max))[0]
    if len(ia) == 0 or len(io) == 0:
        raise ValueError(f"{path.name} has no grid points inside {bounds}")

    base = datetime(2000, 1, 1, tzinfo=timezone.utc)
    if "since" in tunits:
        stamp = tunits.split("since", 1)[1].strip().replace("Z", "")
        for fmt in ("%Y-%m-%d %H:%M:%S", "%Y-%m-%dT%H:%M:%S", "%Y-%m-%d"):
            try:
                base = datetime.strptime(stamp, fmt).replace(tzinfo=timezone.utc)
                break
            except ValueError:
                continue
    times = [base + timedelta(hours=float(h)) for h in toffs]

    return {
        "lats": lat[ia],
        # Report longitudes back in the caller's convention, not the grid's.
        "lons": np.where(lon[io] > 180.0, lon[io] - 360.0, lon[io]),
        "u": u[:, ia][:, :, io],
        "v": v[:, ia][:, :, io],
        "times": times,
        "file": path.name,
    }


def fetch_wind(bounds, start: str, end: str, limit: int = 8,
               cache_dir: Path = CACHE_DIR) -> list[Path]:
    """Download the L4 wind granules covering a window. Cached by filename."""
    from samudra.satellite import live

    m = live.Mosdac()
    r = m.search(WIND_DATASET, start=start, end=end, bbox=tuple(bounds),
                 count=limit)
    out: list[Path] = []
    cache_dir.mkdir(parents=True, exist_ok=True)
    for g in r["granules"][:limit]:
        dest = cache_dir / str(g["identifier"])
        if not dest.exists() or dest.stat().st_size == 0:
            m.download(g["granule_id"], dest)
        out.append(dest)
    return out


def _synthetic_current(shape, lats, lons, seed: int) -> tuple[np.ndarray, np.ndarray]:
    """Smooth, plausible surface current. NOT a measurement — see the docstring."""
    rng = np.random.default_rng(seed)
    nt, nla, nlo = shape
    yy, xx = np.meshgrid(np.linspace(0, 1, nla), np.linspace(0, 1, nlo),
                         indexing="ij")
    phase = rng.uniform(0, 2 * math.pi)
    lo, hi = CURRENT_SPEED_RANGE_MS
    u = np.empty(shape, dtype=np.float32)
    v = np.empty(shape, dtype=np.float32)
    for t in range(nt):
        drift = phase + 0.25 * t
        spd = lo + (hi - lo) * (0.5 + 0.5 * np.sin(2 * math.pi * (xx + yy) + drift))
        ang = drift + 0.9 * np.sin(2 * math.pi * yy) + 0.6 * np.cos(2 * math.pi * xx)
        u[t] = (spd * np.sin(ang)).astype(np.float32)
        v[t] = (spd * np.cos(ang)).astype(np.float32)
    return u, v


def build_env(
    bounds,
    start: datetime,
    end: datetime,
    out_path: Path | str,
    seed: int = 0,
    limit: int = 8,
) -> dict[str, Any]:
    """Assemble env.npz: real EOS-06 wind, synthetic current. Returns provenance."""
    paths = fetch_wind(bounds, start.strftime("%Y-%m-%d"),
                       end.strftime("%Y-%m-%d"), limit=limit)
    if not paths:
        raise RuntimeError(
            f"no {WIND_DATASET} granules returned for {bounds} "
            f"{start:%Y-%m-%d}..{end:%Y-%m-%d}")

    frames = []
    for p in paths:
        try:
            frames.append(read_l4_wind(p, bounds))
        except Exception as exc:  # noqa: BLE001 - one bad granule is not fatal
            print(f"  skipped {p.name}: {exc}")
    if not frames:
        raise RuntimeError("every granule failed to read")

    frames.sort(key=lambda f: f["times"][0])
    lats = frames[0]["lats"]
    lons = frames[0]["lons"]
    u = np.concatenate([f["u"] for f in frames], axis=0).astype(np.float32)
    v = np.concatenate([f["v"] for f in frames], axis=0).astype(np.float32)
    times = [t for f in frames for t in f["times"]]

    # Statistics BEFORE filling. A scatterometer measures the sea surface and
    # returns nothing over land, so most of the missing cells in a coastal AOI
    # are Gujarat, not lost data — measured on the real product, 100% missing at
    # 23.75-24.0 N against 23% at 22.5 N in the middle of the Gulf. Averaging
    # after the fill folds those land cells back in and quietly shifts the
    # number: 7.72 m/s filled against 6.94 m/s over water only, which matters
    # because the detection gate is a 3-10 m/s window.
    no_retrieval = np.isnan(u)
    ocean_speed = np.hypot(u, v)
    stats = {
        "mean_speed_ms": round(float(np.nanmean(ocean_speed)), 2),
        "min_speed_ms": round(float(np.nanmin(ocean_speed)), 2),
        "max_speed_ms": round(float(np.nanmax(ocean_speed)), 2),
    }
    nan_frac = float(no_retrieval.mean())
    if nan_frac:
        # Drift cannot integrate through NaN. Filling with the field's own ocean
        # mean keeps the integrator stable; particles beach before reaching land
        # anyway (impact/landmask.py), so these cells are never actually read.
        u = np.where(no_retrieval, np.nanmean(u), u)
        v = np.where(no_retrieval, np.nanmean(v), v)

    cu, cv = _synthetic_current(u.shape, lats, lons, seed)
    epoch = np.array([t.timestamp() for t in times], dtype=np.float64)

    out = Path(out_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    np.savez_compressed(out, lats=lats, lons=lons, times=epoch,
                        wind_u=u, wind_v=v, curr_u=cu, curr_v=cv)

    prov = {
        "wind": {
            "real": True,
            "satellite": "EOS-06 (Oceansat-3)",
            "instrument": "OSCAT-3 scatterometer",
            "product": WIND_DATASET,
            "provider": "MOSDAC (ISRO), authenticated download",
            "granules": [f["file"] for f in frames],
            "grid_deg": 0.25,
            "time_steps": len(times),
            "window_utc": [times[0].isoformat(), times[-1].isoformat()],
            **stats,
            "no_retrieval_fraction": round(nan_frac, 4),
            "no_retrieval_note": (
                "A scatterometer measures the sea surface and returns nothing "
                "over land, so in a coastal AOI most missing cells are land, "
                "not lost data. Speeds above are over water only, computed "
                "before those cells were filled."),
        },
        "current": {
            "real": False,
            "source": "SYNTHETIC — generated by ingest/environment.py",
            "why": ("MOSDAC publishes no ocean-current product in the set this "
                    "project consumes, and INCOIS's open archive ends in 2023. "
                    "Magnitude is plausible; the field is not a measurement."),
            "speed_range_ms": list(CURRENT_SPEED_RANGE_MS),
            "seed": seed,
        },
        "bounds": list(bounds),
        "written": str(out),
        "acknowledgement": ("MOSDAC / Space Applications Centre, ISRO. "
                            "Acknowledge MOSDAC in any publication using this data."),
    }
    (out.parent / "env_provenance.json").write_text(
        json.dumps(prov, indent=2), encoding="utf-8")
    return prov


def main() -> None:
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")

    ap = argparse.ArgumentParser(
        description="Build env.npz from real EOS-06 wind.")
    ap.add_argument("--incident", help="write into artifacts/<id>/env.npz")
    ap.add_argument("--bounds", help="min_lon,min_lat,max_lon,max_lat")
    ap.add_argument("--hours", type=int, default=48,
                    help="how far back from now to fetch")
    ap.add_argument("--out")
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--limit", type=int, default=8)
    a = ap.parse_args()

    if a.bounds:
        bounds = tuple(float(v) for v in a.bounds.split(","))
    elif a.incident:
        p = Path("artifacts") / a.incident / "incident.json"
        if not p.exists():
            ap.error(f"{p} not found — give --bounds instead")
        bounds = tuple(json.loads(p.read_text())["aoi_bounds"])
    else:
        ap.error("give --bounds or --incident")
    if len(bounds) != 4:
        ap.error("--bounds needs min_lon,min_lat,max_lon,max_lat")

    out = Path(a.out) if a.out else Path("artifacts") / (a.incident or "env") / "env.npz"
    end = datetime.now(timezone.utc)
    start = end - timedelta(hours=a.hours)

    print("=" * 74)
    print("ENVIRONMENT FIELD — real EOS-06 wind, synthetic current")
    print("=" * 74)
    print(f"  bounds     {bounds}")
    print(f"  window     {start:%Y-%m-%d} .. {end:%Y-%m-%d}")
    prov = build_env(bounds, start, end, out, seed=a.seed, limit=a.limit)

    w = prov["wind"]
    print(f"\n  WIND  (REAL)")
    print(f"    {w['satellite']} {w['instrument']}  {w['product']}")
    print(f"    {len(w['granules'])} granule(s), {w['time_steps']} time step(s)")
    print(f"    {w['window_utc'][0]} .. {w['window_utc'][-1]}")
    print(f"    mean {w['mean_speed_ms']} m/s   max {w['max_speed_ms']} m/s")
    print(f"    range {w['min_speed_ms']}-{w['max_speed_ms']} m/s (over water)")
    if w["no_retrieval_fraction"]:
        print(f"    no retrieval over {w['no_retrieval_fraction'] * 100:.1f}% "
              f"of cells — mostly land, see note in env_provenance.json")
    print(f"\n  CURRENT  (SYNTHETIC)")
    print(f"    {prov['current']['why'][:68]}...")
    print(f"\n  written  {prov['written']}")
    print(f"  {prov['acknowledgement']}")


if __name__ == "__main__":
    main()
